backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /images

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Privacy Page"
        name: "privacy"
        file: "src/pages/privacy.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}

  - name: "menu" # Used in routes, e.g., /admin/collections/blog
    label: "Menu" # Used in the UI
    folder: "src/pages/menu" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "menu"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "MenuSection", name: "menusection", widget: "select", options: ["entrees", "mains", "specials"], required: false}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Discount", name: "discount", widget: "string"}
      - {label: "GlutenFree", name: "glutenfree", widget: "boolean", default: false}
      - {label: "OutofStock", name: "outofstock", widget: "boolean", default: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Featured Image Alt Text", name: "thumbnailAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "sale"
    label: "Sale"
    folder: "src/pages/sale"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "sale"}
      - {label: "Start Date", name: "startdate", widget: "datetime"}
      - {label: "End Date", name: "enddate", widget: "datetime"}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Featured Image Alt Text", name: "thumbnailAlt", widget: "string"}
      - required: false
        label: "MenuItem"
        name: "menuitem"
        widget: "object"
        fields: 
          - {name: menuitemtitle,label: MenuItemsTitle,widget: relation,collection: menu,
            entry: title,searchFields: ['title'],multiselect: true,valueField: "title",displayFields: ["title"]}
          - {name: menuitemdesc,label: MenuItemsDesc,widget: relation,collection: menu,
            entry: description,searchFields: ['title'],multiselect: true,valueField: "description",displayFields: ["title"]}
          - {name: menuitempath,label: MenuItemsPath,widget: relation,collection: menu,
            entry: path,searchFields: ['title'],multiselect: true,valueField: "path",displayFields: ["title"]}


